labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      placeholder: Explain how to reproduce the bug
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Affected parts
      description: "Which part of OS does it affect?"
      options:
        - label: "BootLoader part1"
        - label: "BootLoader part2"
        - label: "Kernel"
  - type: input
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what you expected to happen
    validations:
      required: true
  - type: input
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened
      placeholder: Describe what actually happened
    validations:
      required: true
  - type: input
    attributes:
      label: "Virtualization"
      description: "If applicable what virtualization are you using?"
      placeholder: "e.g. QEMU"
  - type: input
    attributes:
      label: "Host OS"
      description: "If applicable what host OS are you using?"
      placeholder: "e.g. Ubuntu 20.04, Windows 11 22H2"
  - type: input
    attributes:
      label: "Device"
      description: "What device are you using?"
      placeholder: "model (e.g. ASUS UX305UAB) or specs (RAM, CPU, etc.)"
    validations:
      required: true
  - type: input
    attributes:
      label: "BIOS"
      description: "What BIOS/EFI are you using?"
      placeholder: "e.g. ASUS UEFI, SeaBIOS"
    validations:
      required: true
  - type: input
    attributes:
      label: "Error code"
      description: "If given what error code are you getting?"
      placeholder: "e.g. 0x0000007B"
  - type: input
    attributes:
      label: "OS version"
      description: "What OS version are you using?"
      placeholder: "tag (e.g. kernel-prev2) or commit (e.g. a50f32e)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots and logs"
      description: "If you got any screenshots or logs add them here."
      placeholder: "files, links, etc."
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."