name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Solution description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternatives you've considered
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.