name: Vulnerability report
description: File a vulnerability report
labels: [vulnerability ]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this vulnerability?
      options:
        - Medium
        - High
        - Urgent
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of vulnerability
      placeholder: Describe the vulnerability
    validations:
      required: true
  - type: textarea
    attributes:
      label: Affected
      description: A clear and concise description of what is affected by this vulnerability
    validations:
      required: true
  - type: input
    attributes:
      label: "OS version"
      description: "What OS version are you using?"
      placeholder: "tag (e.g. kernel-prev2) or commit (e.g. a50f32e)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Logs"
      description: "If you got any logs add them here."
      placeholder: "files, links, etc."
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."